# Generated by Django 4.2 on 2023-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("descriptin", models.TextField()),
                ("input_format", models.CharField(max_length=100)),
                ("output_format", models.CharField(max_length=100)),
                ("hint", models.CharField(max_length=400)),
                ("language", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
