# Generated by Django 4.2 on 2023-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_rename_descriptin_problem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="input_format",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="problem",
            name="language",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="problem", name="level", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="problem",
            name="output_format",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="problem", name="title", field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="problem", name="type", field=models.CharField(max_length=100),
        ),
    ]
