# Generated by Django 4.2 on 2023-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="username",),
        migrations.AlterField(
            model_name="customuser",
            name="dept",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
